name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.9", "3.10", "3.11"]

      steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install tld beautifulsoup4

      - name: Test with unittest
        run: |
          python -m unittest discover test

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: pypi
      url: https://pypi.org/p/ready-check
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install test dependencies
        run: |
          pip install -e '.'

      - name: Install publishing dependencies
        run: |
          pip install setuptools wheel twine build

      - name: Build python package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
